# Generated by Django 4.2.1 on 2023-06-02 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no', to=settings.AUTH_USER_MODEL),
        ),
    ]
