# Generated by Django 4.2.1 on 2023-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
