# Generated by Django 4.2.1 on 2023-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0002_departments_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='location',
            field=models.CharField(default='Yassin', max_length=60),
        ),
    ]
